# Generated by Django 4.1.4 on 2022-12-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept_map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.AddField(
            model_name='node',
            name='connections',
            field=models.ManyToManyField(blank=True, to='concept_map.node'),
        ),
    ]
