# Generated by Django 4.1.4 on 2023-01-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept_map', '0002_remove_node_connections_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
