# Generated by Django 4.1.4 on 2023-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept_map', '0003_node_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='category',
            field=models.CharField(default='Idea', max_length=50),
        ),
    ]
